# Colores

foreground              #f2f2f2
background              #101010

# Cursor (opcional, puedes ajustar luego)
cursor                  #ffffff

# Colores normales
color0  #181a29
color1  #F07178
color2  #cdea9f
color3  #ffd47e
color4  #93bbff
color5  #d3a7ee
color6  #98e4ff
color7  #bfd5de

# Colores brillantes
color8  #282a40
color9  #eb7f84
color10 #e0ffad
color11 #ffee7e
color12 #a3c5ff
color13 #d6afed
color14 #98fffd
color15 #d1e5ed

# Fuente
font_family      UbuntuMono Nerd Font
bold_font        UbuntuMono Nerd Font
italic_font      UbuntuMono Nerd Font
font_size        17

# Opacidad
background_opacity 0.55

# Padding
window_padding_width 10
window_padding_height 10

allow_remote_control yes

#dpi
